[project]
name = "zfish-cilia-csf"
version = "0.0.1"
requires-python = ">=3.8"

# Path to README.md
readme = "README.md"

# Path to license file
license = {file = "LICENSE"}

# Direct dependencies
dependencies = [
    'multiphenicsx@git+https://github.com/multiphenics/multiphenicsx.git'
]
