name: Test zebrafish-cilia-csf flow and transport codes
on:
  workflow_dispatch:
  workflow_call:
  pull_request:
    branches: ["main"]

env:
  DEB_PYTHON_INSTALL_LAYOUT: deb_system

defaults:
  run:
    shell: bash -el {0}

jobs:
  test_scripts:
    runs-on: ubuntu-latest
    container: ubuntu:latest

    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          DEBIAN_FRONTEND=noninteractive apt-get update
          DEBIAN_FRONTEND=noninteractive apt-get install -y unzip make build-essential git libgmp-dev
      - name: Setup conda-forge
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: "3.13"

      - name: Setup conda environment
        run: |
          conda create -n zfish-cilia-csf-env python=3.13
          conda activate zfish-cilia-csf-env
          conda env update --file environment.yml --prune

      - name: Run flow code to test build
        run: |
          conda activate zfish-cilia-csf-env
        # Not enough memory to perform this:
        # cd ./src
        # python3 simulate_flow.py 0